version: "3.8"

services:
  guppe:
    build: .
    restart: always
    ports:
      - 8085:8085
    env_file: '.env'
    environment:
      DB_URL: 'mongodb://mongodb:27017'
    depends_on:
      - mongodb
    volumes:
      # localdev certs
      - ./certs:/usr/src/guppe/certs
    logging:
      driver: local
      options:
        max-size: '10m'

  mongodb:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db
    logging:
      driver: local
      options:
        max-size: '10m'

volumes:
  mongo-data:
